name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate1:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código (forçando erro)
        run: exit 1  # Força falha

  validate2:
    runs-on: ubuntu-latest
    steps:
      - name: Outro job de validação (forçando erro)
        run: exit 1  # Força falha

  notify-slack:
    runs-on: ubuntu-latest
    needs: [validate1, validate2]  # Espera os outros jobs terminarem
    if: always()  # Sempre executa para verificar falhas
    steps:
      - name: Identificar jobs que falharam
        id: failed-jobs
        run: |
          FAILED_JOBS=""
          if [ "${{ needs.validate1.result }}" == "failure" ]; then
            FAILED_JOBS="validate1"
          fi
          if [ "${{ needs.validate2.result }}" == "failure" ]; then
            FAILED_JOBS="${FAILED_JOBS} validate2"
          fi
          echo "FAILED_JOBS=${FAILED_JOBS}" >> $GITHUB_ENV

      - name: Notificar Slack em caso de erro
        if: env.FAILED_JOBS != ''
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "message": "Falha na validação da PR",
              "author":  "${{ github.event.pull_request.user.login }}",
              "pull_request_name": "${{ github.event.pull_request.title }}",
              "pull_request_link":   "${{ github.event.pull_request.html_url }}",
              "failed_jobs": "${{ env.FAILED_JOBS }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
