name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate1:
    runs-on: ubuntu-latest
    steps:
      - name: Check code (forcing error)
        run: exit 1  # Forces failure

  validate2:
    runs-on: ubuntu-latest
    steps:
      - name: Another validation job (forcing error)
        run: exit 0

  notify-slack:
    runs-on: ubuntu-latest
    needs: [validate1, validate2]  # Waits for the other jobs to finish
    if: always()  # Always runs to check for failures
    steps:
      - name: Identify failed jobs
        id: failed-jobs
        run: |
          FAILED_JOBS=""
          
          if [ "${{ needs.validate1.result }}" == "failure" ]; then
            FAILED_JOBS="validate1"
          fi

          if [ "${{ needs.validate2.result }}" == "failure" ]; then
            FAILED_JOBS="${FAILED_JOBS} validate2"
          fi

          echo "FAILED_JOBS=${FAILED_JOBS}" >> $GITHUB_ENV

      - name: Notify Slack in case of error
        if: env.FAILED_JOBS != ''
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "message": "Pull Request validation failed",
              "author":  "${{ github.event.pull_request.user.login }}",
              "pull_request_name": "${{ github.event.pull_request.title }}",
              "pull_request_link":   "${{ github.event.pull_request.html_url }}",
              "failed_jobs": "${{ env.FAILED_JOBS }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
