name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código (forçando erro)
        run: exit 1  # Isso força a falha

      - name: Notificar Slack em caso de erro
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "⚠️ *Falha na validação da PR*",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  { "title": "Autor", "value": "${{ github.event.pull_request.user.login }}", "short": true },
                  { "title": "Título", "value": "${{ github.event.pull_request.title }}", "short": false },
                  { "title": "Link", "value": "<${{ github.event.pull_request.html_url }}|Ver PR>", "short": false }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
