name: PR Validation

on:
  pull_request:
    types: [opened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código (forçando erro)
        run: exit 1  # Isso força a falha

      - name: Notificar Slack em caso de erro
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
        env:
          SLACK_MESSAGE: >
            {
              "text": "⚠️ *Falha na validação da PR*",
              "attachments": [
                {
                  "color": "danger",
                  "fields": [
                    { "title": "Autor", "value": "${{ github.event.pull_request.user.login }}", "short": true },
                    { "title": "Título da PR", "value": "${{ github.event.pull_request.title }}", "short": true },
                    { "title": "Link da PR", "value": "${{ github.event.pull_request.html_url }}", "short": false }
                  ]
                }
              ]
            }
